name: example
description: A new Flutter project to test interactive image.
publish_to: 'none' 
version: 1.0.2+3

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #share_plus: ^4.0.10+1
  #flutter_map: ^6.1.0
  flutter_form_builder: ^9.1.1
  file_picker: ^6.1.1
  path_provider: ^2.1.2

  interactive_image:
    path: ../
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true