name: example
description: A new Flutter project to test interactive image.
publish_to: 'none' 
version: 1.0.2+3

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_form_builder: ^9.3.0
  file_picker: ^8.0.6
  path_provider: ^2.1.3

  interactive_image:
    path: ../
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true