name: example
description: A new Flutter project to test interactive image.
publish_to: 'none' 
version: 1.0.3+4

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_form_builder: ^10.2.0
  file_picker: ^10.3.3
  path_provider: ^2.1.3

  interactive_image:
    path: ../
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true