name: example
description: A new Flutter project to test interactive image.
publish_to: 'none' 
version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <4.0.20"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  share_plus: ^4.0.10+1
  flutter_map: ^5.0.0
  flutter_form_builder: ^7.5.0
  file_picker: ^5.0.1
  path_provider: ^2.0.11

  interactive_image:
    path: ../
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

