name: interactive_image
description: Interactive image widget for simple indoor maps.
# pub.dev using `flutter pub publish`.
version: 8.0.0
repository: https://github.com/dariocavada/interactive_image

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5

  flutter_map: ^8.2.2
  flutter_map_dragmarker: ^8.0.3
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  
