name: interactive_image
description: Interactive image widget for simple indoor maps.
version: 0.0.3
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.1.2
  cached_network_image: ^3.1.0
  path_provider: ^2.0.2
  flutter_map: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
