name: interactive_image
description: Interactive image widget for simple indoor maps.
version: 5.0.0
repository: https://github.com/dariocavada/interactive_image

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  path_provider: ^2.0.15
  flutter_map: ^5.0.0
  flutter_map_dragmarker: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
