name: interactive_image
description: Interactive image widget for simple indoor maps.
version: 0.0.6
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.1
  path_provider: ^2.0.11
  flutter_map: ^2.2.0
  flutter_map_dragmarker: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
